//
// Created by mano on 10.12.16.
//

#ifndef PORTFORWARDERREDEAWROFTROP_CONSTANTS_H
#define PORTFORWARDERREDEAWROFTROP_CONSTANTS_H

#define LITTLE_STRING_SIZE 4096
#define DEFAULT_BUFFER_SIZE (4096)
#define DEFAULT_PORT 80

#define RESULT_CORRECT 1
#define RESULT_INCORRECT -1

#define IP_ADDRESS "87.98.147.22"

#endif //PORTFORWARDERREDEAWROFTROP_CONSTANTS_H
